version: "3.9"
services:
  frontend:
      ports:
        - 3000:3000
      build:
        context: ./frontend
        dockerfile: Dockerfile
      env_file:
        - .env
  backend:
      ports:
        - 3001:3001
      build:
        context: ./backend
        dockerfile: Dockerfile
      env_file:
        - .env
      depends_on:
        - postgres
  postgres:
        image: postgres:15.1
        restart: always
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=test1234
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql